apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker2-bhth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker2-bhth
    app.kubernetes.io/part-of: q
  name: java-quarkus-hello-dockerwxvq
  namespace: burrzinga-hac-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-quarkus-hello-docker2-bhth
    weight: null
status: {}
